### ISSUE TITLE
PDF下载失败

### ISSUE THREAD

**Issue by viccccctu** [qiye45/wechatDownload#30]
您好，导出pdf和word会弹出提示【下载成功】，但日志里不显示，下载目录里也没有。

**Comment by viccccctu** [comment]
> 选上html
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月12日(周二) 晚上10:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/wechatDownload] PDF下载失败 (Issue #30) 您好，导出pdf和word会弹出提示【下载成功】，但日志里不显示，下载目录里也没有。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

您好，选上html，下载目录里也只有html文件，没有pdf和docx。

**Comment by qiye45** [comment]
重新下载一下2.2试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] PDF下载失败 (Issue #30)




  
选上html
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月12日(周二) 晚上10:02 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] PDF下载失败 (Issue #30) 您好，导出pdf和word会弹出提示【下载成功】，但日志里不显示，下载目录里也没有。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
您好，选上html，下载目录里也只有html文件，没有pdf和docx。
