### ISSUE TITLE
只导出url和标题的表格不用下载内容或者评论数

### ISSUE THREAD

**Issue by ChitaGideon** [qiye45/wechatDownload#62]
只导出url和标题的表格不用下载内容或者评论数
这样是不是会快很多。

现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中

**Comment by qiye45** [comment]
等一会咯 (=・ω・=)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 上午9:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62)




 
只导出url和标题的表格不用下载内容或者评论数
 这样是不是会快很多。
 
现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中

**Comment by ChitaGideon** [comment]
> 等一会咯 (=・ω・=)
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪

**Comment by qiye45** [comment]
截个图看看吧，选上时间段试一试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62)




  
等一会咯 (=・ω・=)
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪

**Comment by ChitaGideon** [comment]
> 截个图看看吧，选上时间段试一试
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月23日(周二) 上午10:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 等一会咯 (=・ω・=) … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

<img width="865" alt="image" src="https://github.com/qiye45/wechatDownload/assets/1167456/0026635a-2d7d-4e80-84a6-4b83848e0c01">
就是卡住  不动，也不懂出什么问题

**Comment by qiye45** [comment]
把等待时间调高一点试一试，60秒以上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62)




  
等一会咯 (=・ω・=)
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪

**Comment by node-chita** [comment]
不太行。60秒也几乎一定会在某篇文章卡住；
我看点赞数好像都是2.3版本加入的；那2.2版本的导出表格是不是就只有url了？
那我自己用2.2版本能用吗？


> 把等待时间调高一点试一试，60秒以上
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月23日(周二) 上午10:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 等一会咯 (=・ω・=) … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by qiye45** [comment]
试试旧版本咯(=・ω・=)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 中午12:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62)




 
不太行。60秒也几乎一定会在某篇文章卡住；
 我看点赞数好像都是2.3版本加入的；那2.2版本的导出表格是不是就只有url了？
 那我自己用2.2版本能用吗？
  
把等待时间调高一点试一试，60秒以上
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午10:46 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 等一会咯 (=・ω・=) … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月23日(周二) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 只导出url和标题的表格不用下载内容或者评论数 这样是不是会快很多。 现在我把这些选项全部取消掉之后，还是会很慢，明明不需要保持文章，还是要显示保存文章中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 文章少的话，就等下了，但文章多的时候，慢太多了；保存文章好像还会卡住不动，因为我没选保存文章，也不懂卡在哪 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;

**Comment by qiye45** [comment]
发一下链接，我试试吧

**Comment by ChitaGideon** [comment]
> 发一下链接，我试试吧

这[公众号文章](https://mp.weixin.qq.com/s/9rkkflYjUMe1vXNKofYLHQ)很多，我需要的是到19年的url；因为文章很多，又没有在某个地方恢复的功能，经常卡了之后，就只能从头再来，几乎很难成功。

**Comment by qiye45** [comment]
选一下时间段试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 晚上9:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62)




  
发一下链接，我试试吧
  
这公众号文章很多，我需要的是到19年的url；因为文章很多，又没有在某个地方恢复的功能，经常卡了之后，就只能从头再来，几乎很难成功。

**Comment by ChitaGideon** [comment]
> 选一下时间段试试
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月24日(周三) 晚上9:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qiye45/wechatDownload] 只导出url和标题的表格不用下载内容或者评论数 (Issue #62) 发一下链接，我试试吧 这公众号文章很多，我需要的是到19年的url；因为文章很多，又没有在某个地方恢复的功能，经常卡了之后，就只能从头再来，几乎很难成功。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

选时间段似乎也没啥影响，除非选得够短，因为每次都是从头开始的，前几个月都没问题，后面就很容易卡了，好像也没一个功能，在卡住的地方，开始继续

**Comment by qiye45** [comment]
下载失败的问题，可以关注这个issue哟 https://github.com/qiye45/wechatDownload/issues/74
