### ISSUE TITLE
下载的推送只显示“环境异常 当前环境异常，完成验证后即可继续访问。”，无论word还是html

### ISSUE THREAD

**Issue by jiangdongni** [qiye45/wechatDownload#79]
![微信截图_20240429105056](https://github.com/qiye45/wechatDownload/assets/168390148/86d094c7-b75b-41ed-b2b1-16bca4e01502)

**Comment by qiye45** [comment]
软件截个图看看，带上链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 下载的推送只显示“环境异常 当前环境异常，完成验证后即可继续访问。”，无论word还是html (Issue #79)




 
_20240429105056.png (view on web)

**Comment by jiangdongni** [comment]
![微信截图_20240430081301](https://github.com/qiye45/wechatDownload/assets/168390148/16ce6903-3a95-47ef-b201-42b65e006bca)
链接：https://mp.weixin.qq.com/s/hpDTF_dsjpt3yFS4_O20OA

**Comment by qiye45** [comment]
用2.4，新版本修复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月30日(周二) 下午3:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 下载的推送只显示“环境异常 当前环境异常，完成验证后即可继续访问。”，无论word还是html (Issue #79)




  
软件截个图看看，带上链接
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月29日(周一) 上午10:57 收件人: @.&gt;; 抄送: @.&gt;; 主题: [qiye45/wechatDownload] 下载的推送只显示“环境异常 当前环境异常，完成验证后即可继续访问。”，无论word还是html (Issue #79) _20240429105056.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
_20240430081301.png (view on web)
 
链接：https://mp.weixin.qq.com/s/hpDTF_dsjpt3yFS4_O20OA
